name: CondensePlugin
version: '${project.version}'
main: me.kermx.condenseplugin.CondensePlugin
api-version: '1.20'
commands:
  condense:
    usage: /condense <item/all>
    permission: condenseplugin.use
    description: Condense items into their block form
    aliases:
      - cond
      - smush
      - c
  uncondense:
    usage: /uncondense <item/all>
    permission: uncondenseplugin.use
    description: Uncondense items into their item form, from block
    aliases:
      - uncond
      - unsmush
      - unc
      - uc
